- name: Create tensorflow's user
  user:
    name: "{{ tensorflow.user.name }}"
    groups: "{{ tensorflow.user.secondary_groups }}"
    home: "{{ tensorflow.user.home }}"
  become: yes
- name: Install conda
  ansible.legacy.aur:
    use: yay
    name: miniconda3
  become: yes
  become_user: "{{ aur_builder.user.name }}"
- name: "Setup conda environment with tensorflor for user {{ tensorflow.user.name }}"
  block:
    - name: "Ensure directory {{ tensorflow.user.home }}/conda exists"
      file:
        path: "{{ tensorflow.user.home }}/conda"
        state: directory
    - name: "Copy environment file to host machine {{ tensorflow.user.home }}/conda"
      copy:
        src: environment.yml
        dest: "{{ tensorflow.user.home }}/conda/environment.yml"
        owner: "{{ tensorflow.user.name }}"
        group: "{{ tensorflow.user.name }}"
    # Path for conda is hardocded because otherwise "conda: command not found" error will be encounterd
    # This path depends on the conda package it will change if the package providing conda has been changed
    - name: Create conda environment from file - tensor_env
      shell: "/opt/miniconda3/bin/conda env create --force -f {{ tensorflow.user.home }}/conda/environment.yml"
    - name: Init conda - source conda in user's .bashrc
      lineinfile:
        path: "{{ tensorflow.user.home }}/.bashrc"
        line: '[ -f /opt/miniconda3/etc/profile.d/conda.sh ] && source /opt/miniconda3/etc/profile.d/conda.sh'
  become: yes
  become_user: "{{ tensorflow.user.name }}"
